---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        files: \.(yml|yaml)$
      - id: detect-private-key

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: check-ansible-vault
        name: Check Ansible Vault Encryption
        entry: bash check_ansible_vault.sh
        language: system
        files: (^|/)vault/.*$
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: add-yaml-document-start
        name: Add YAML document start if missing
        entry: bash add-yaml-document-start.sh
        language: system
        files: \.(yml|yaml)$
        stages: [pre-commit]

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.1.1
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - jmespath

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.(yml|yaml)$

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
