---
- name: Préparer la résolution DNS
  hosts: all
  become: true
  tasks:
    - name: Stop systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: false

    - name: Remplacer resolv.conf
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 9.9.9.9
          nameserver 8.8.8.8
          nameserver 1.1.1.1
        force: true
        mode: '0644'

- name: Set up Kubernetes components
  hosts: kube_cluster
  become: true
  pre_tasks:
    - name: Gather service state information as fact data
      ansible.builtin.service_facts:
      tags:
        - always
  # - name: Print services facts
  #   ansible.builtin.debug:
  #     var: ansible_facts.services
  roles:
    - role: cfg_nodes
      tags:
        - cfg_nodes
    - role: inst_runc
      tags:
        - inst_runc
    - role: inst_cni
      tags:
        - inst_cni
    - role: cfg_containerd
      tags:
        - cfg_containerd
    - role: inst_cri_tools
      tags:
        - inst_cri_tools
    - role: cfg_kubeadm_kubelet_kubectl
      tags:
        - cfg_kubeadm_kubelet_kubectl

- name: Initialize Kubernetes control plane on primary node
  hosts: kube_controlplan
  become: true
  roles:
    - role: init_kubeadm
      tags:
        - init_kubeadm
    - role: kubectl_cheat_sheet
      tags:
        - kubectl_cheat_sheet

- name: Join the workers/agents
  hosts: kube_workers
  become: true
  roles:
    - role: join_workers
